<a href="https://colab.research.google.com/github/subarna007/Data-Warehouse-Assignment/blob/main/subarna_lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/pre-Data.csv')

In [ ]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
dataset.isna()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [ ]:
dataset.isna().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
dataset_1 = dataset.dropna()

In [ ]:
dataset_1

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
dataset.fillna(dataset.mean(),inplace=True)

In [ ]:
dataset

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [ ]:
dataset['Age'].fillna(dataset['Age'].mean(),inplace=True)
dataset['Salary'].fillna(dataset['Salary'].mean(),inplace=True)

In [ ]:
dataset

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [ ]:
X = dataset.iloc[:,[0,1,2]]   #or X=dataset.iloc[:,:-1]
Y = dataset.iloc[:,[3]]  #or Y=dataset.iloc[:,-1:]

In [ ]:
#Task: 
#1. Create set X_1 of Country column from the dataset
#X_1= 
#2. Create set X_2 of Age and Salary columns from the dataset
#3. Create set X_3 of first five records in the dataset

In [ ]:
#Task:
#1. Create set X_1 of Country column from the dataset
X_1= dataset.iloc[:,[0]]

In [ ]:
X_1

Country
0   France
1    Spain
2  Germany
3    Spain
4  Germany
5   France
6    Spain
7   France
8  Germany
9   France

In [ ]:
#2. Create set X_2 of Age and Salary columns from the dataset
X_2= dataset.iloc[:,[1,2]]

In [ ]:
X_2

Age        Salary
0  44.000000  72000.000000
1  27.000000  48000.000000
2  30.000000  54000.000000
3  38.000000  61000.000000
4  40.000000  63777.777778
5  35.000000  58000.000000
6  38.777778  52000.000000
7  48.000000  79000.000000
8  50.000000  83000.000000
9  37.000000  67000.000000

In [ ]:
#3. Create set X_3 of first five records in the dataset
x_3=dataset.iloc[:5]

In [ ]:
x_3

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes

In [ ]:
#X = dataset.iloc[:,[0,1,2]] #or X=dataset.iloc[:,:-1]
#Y = dataset.iloc[:,[3]]
#or Y=dataset.iloc[:,-1:]

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lEncoder = LabelEncoder()

In [ ]:
X.iloc[:,0] = lEncoder.fit_transform(X.iloc[:,0])

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)


In [ ]:
X

Country        Age        Salary
0        0  44.000000  72000.000000
1        2  27.000000  48000.000000
2        1  30.000000  54000.000000
3        2  38.000000  61000.000000
4        1  40.000000  63777.777778
5        0  35.000000  58000.000000
6        2  38.777778  52000.000000
7        0  48.000000  79000.000000
8        1  50.000000  83000.000000
9        0  37.000000  67000.000000

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
Onehotencoder = OneHotEncoder()
Onehotencoder = OneHotEncoder(['Country']) #one way of encoding

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0])],   remainder='passthrough')

In [ ]:
X=np.array(columnTransformer.fit_transform(X),dtype=np.float)

In [ ]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [ ]:
#Now we got our independent variable X in the form of numpy array. 
#same can we check with the help of type(X). 
#just for to showing you how X look like we will converted into Pandas Dataframe with the use of below code.

In [ ]:
pd.DataFrame(X,dtype=int)

0  1  2   3      4
0  1  0  0  44  72000
1  0  0  1  27  48000
2  0  1  0  30  54000
3  0  0  1  38  61000
4  0  1  0  40  63777
5  1  0  0  35  58000
6  0  0  1  38  52000
7  1  0  0  48  79000
8  0  1  0  50  83000
9  1  0  0  37  67000

In [ ]:
labelEncoder_Y = LabelEncoder()
Y.iloc[:,0] = labelEncoder_Y.fit_transform(Y.iloc[:,0])

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1781: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item_labels[indexer[info_axis]]] = value


In [ ]:

Y

Purchased
0          0
1          1
2          0
3          0
4          1
5          1
6          0
7          1
8          0
9          1

In [ ]:
#Now we got X and Y both are in encoded form, now both can be apply on Machine Learning model.

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
#splitting X and Y dataset into train and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state=0)

In [ ]:
X_train

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04]])

In [ ]:
X_test

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04]])

In [ ]:
Y_train

Purchased
9          1
1          1
6          0
7          1
3          0
0          0
5          1

In [ ]:
Y_test

Purchased
2          0
8          0
4          1

In [ ]:
#We will apply the formula of standardization and fit it to a scale. 
#For this, we will import the class StandardScaler from the sckit preprocessing library and as usual create an object of that class.
from sklearn.preprocessing import StandardScaler

In [ ]:
sc_x = StandardScaler()

In [ ]:
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.fit_transform(X_test)

In [ ]:
X_train

array([[ 0.8660254 ,  0.        , -0.8660254 , -0.2029809 ,  0.44897083],
       [-1.15470054,  0.        ,  1.15470054, -1.82168936, -1.41706417],
       [-1.15470054,  0.        ,  1.15470054,  0.08478949, -1.0242147 ],
       [ 0.8660254 ,  0.        , -0.8660254 ,  1.5775984 ,  1.62751925],
       [-1.15470054,  0.        ,  1.15470054, -0.04111006, -0.14030338],
       [ 0.8660254 ,  0.        , -0.8660254 ,  0.93011502,  0.94003267],
       [ 0.8660254 ,  0.        , -0.8660254 , -0.52672259, -0.43494049]])

In [ ]:
X_test

array([[ 0.        ,  0.        ,  0.        , -1.22474487, -1.07298811],
       [ 0.        ,  0.        ,  0.        ,  1.22474487,  1.33431759],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.26132948]])

In [ ]:
#Task: Use min max scaling for feature scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from numpy import asarray

In [ ]:
data = asarray(X_train)

In [ ]:
print(data)

[[ 0.8660254   0.         -0.8660254  -0.2029809   0.44897083]
 [-1.15470054  0.          1.15470054 -1.82168936 -1.41706417]
 [-1.15470054  0.          1.15470054  0.08478949 -1.0242147 ]
 [ 0.8660254   0.         -0.8660254   1.5775984   1.62751925]
 [-1.15470054  0.          1.15470054 -0.04111006 -0.14030338]
 [ 0.8660254   0.         -0.8660254   0.93011502  0.94003267]
 [ 0.8660254   0.         -0.8660254  -0.52672259 -0.43494049]]


In [ ]:
scaler = MinMaxScaler()

In [ ]:
scaled = scaler.fit_transform(data)

In [ ]:
print(scaled)

[[1.         0.         0.         0.47619048 0.61290323]
 [0.         0.         1.         0.         0.        ]
 [0.         0.         1.         0.56084656 0.12903226]
 [1.         0.         0.         1.         1.        ]
 [0.         0.         1.         0.52380952 0.41935484]
 [1.         0.         0.         0.80952381 0.77419355]
 [1.         0.         0.         0.38095238 0.32258065]]
